### DISCUSSION TITLE
How to run rsspls in a Docker container?

### DISCUSSION THREAD

**Discussion by YanisKyr** [wezm/rsspls#60] [General]
Is it possible to run rsspls in a Docker container?

**Comment by wezm** [comment]
Yes it's possible, I run it in Docker myself via docker-compose. This is the `Dockerfile` I use (note that the base image is not public but can be substituted with one of the alpine images on Docker Hub):

```dockerfile
FROM wezm-alpine:3.20.3

# UID needs to match owner of /home/rsspls/feeds volume
ARG PUID=1000
ARG PGID=1000
ARG USER=rsspls

RUN addgroup -g ${PGID} ${USER} && \
    adduser -D -u ${PUID} -G ${USER} -h /home/${USER} -D ${USER}

ARG RSSPLS_VERSION=0.9.0

RUN cd /usr/local/bin && \
    wget -O - https://releases.wezm.net/rsspls/${RSSPLS_VERSION}/rsspls-${RSSPLS_VERSION}-x86_64-unknown-linux-musl.tar.gz | tar zxf - && \
    mkdir /home/${USER}/feeds && \
    chown ${USER}:${USER} /home/${USER}/feeds

COPY ./entrypoint.sh /home/${USER}/entrypoint.sh

WORKDIR /home/${USER}

USER ${USER}

VOLUME ["/home/rsspls/feeds"]
ENTRYPOINT ["./entrypoint.sh"]
````

The `entrypoint.sh` script is:

```sh
#!/bin/sh

set -e

trap 'exit' TERM INT

while true; do
  rsspls --config /etc/rsspls.toml
  sleep 1036800 # 12 hours
done
```

The `docker-compose.yaml` section for rsspls looks like this. Note that it supplies the config file via a volume. Also not that the image mentioned there is not public either.

```yaml
  rsspls:
    image: 791569612186.dkr.ecr.ap-southeast-2.amazonaws.com/rsspls
    volumes:
      - ./rsspls/rsspls.toml:/etc/rsspls.toml:ro
      - ./volumes/www/rsspls.wezm.net:/home/rsspls/feeds
    restart: unless-stopped
```
