### ISSUE TITLE
Specifying the default time zone in `feed.config.date`

### ISSUE THREAD

**Issue by trustin** [wezm/rsspls#23]
Hello! :wave: It'd be nice if there a way to specify the time zone of the selected datetime text. `rsspls` currently assume UTC, which is not always correct.

**Comment by wezm** [comment]
So this would be for when the actual text does not contain a time zone I assume?

I imagine an optional field on the date table might work?

```toml
[feed.config.date]
selector = "time"
type = "DateTime"
format = "[day padding:none]/[month padding:none]/[year] [hour repr:24]:[minute]"
timezone = "UTC+10"
```
