### ISSUE TITLE
Add key-value argument for dynamic feed config

### ISSUE THREAD

**Issue by Lcchy** [wezm/rsspls#33]
Hi there,

For my personal usage I have been adding a feature to the feeds config.

I am subscribing to a website that has different "profiles" (a bit like mastodon or instagram).
The website is the same but the content is different for each profile and I would like to subscribe to different profiles as separate feeds.

I could duplicate the feed config in the `feeds.toml` but I have close to 100 subscriptions so that would become cumbersome.

That is why I implemented this feature which enables the passing of an arbitrary key-value parameter that will be inserted into the config.

Example:

`rsspls --parameter username=john`

with the config:

```
[rsspls]

[[feed]]
title = "%<username> - Feed"
filename = "feed_%<username>.rss"

[feed.config]
url = "https://www.example.com/profile/%<username>/"
...
```

will simply replace the "%<username>" with "john" and then generate the feed as before.

I already opened the PR so thats its easier to discuss, but feel free to reject it if you don't think its applicable.

**Comment by wezm** [comment]
Hmm I appreciate the solid use case but I not sure introducing templating is the way to go. It kinda feels like an external tool that generated the config would be a better option. It would also have the benefit of fetching multiple feeds in parallel.

I've recently been playing with [Nickel](https://nickel-lang.org/) and it would be pretty neat for doing this. Of course you could do similar with a Python script or something. E.g.

if you had `accounts.json` (or `accounts.toml`) with the accounts you wanted follow like:

```json
{
  "accounts": [
    "one",
    "two",
    "three"
  ]
}
```

You could generate `rsspls.toml` using Nickel code like this:

```nickel
let accounts = import "accounts.json" in

let account_feed = fun account =>
  {
    title = "Posts from %{account}",
    filename = "%{account}.rss",
    config = {
      url = "https://example.com/user/%{account}",
      item = "article",
      heading = "h3",
      link = "h3 a",
      summary = ".post-body",
      date = "time"
    }
  }
in

{
  rsspls = {
    output = "/tmp"
  },
  feed = std.array.map account_feed accounts
}
```

The config would be generated with `nickel export -f toml rsspls.ncl`, which from the above two files looks like this:

```toml
[[feed]]
filename = "one.rss"
title = "Posts from one"

[feed.config]
date = "time"
heading = "h3"
item = "article"
link = "h3 a"
summary = ".post-body"
url = "https://example.com/user/one"

[[feed]]
filename = "two.rss"
title = "Posts from two"

[feed.config]
date = "time"
heading = "h3"
item = "article"
link = "h3 a"
summary = ".post-body"
url = "https://example.com/user/two"

[[feed]]
filename = "three.rss"
title = "Posts from three"

[feed.config]
date = "time"
heading = "h3"
item = "article"
link = "h3 a"
summary = ".post-body"
url = "https://example.com/user/three"

[rsspls]
output = "/tmp"
```
