### ISSUE TITLE
400 Bad Request for a valid url

### ISSUE THREAD

**Issue by mach-o** [wezm/rsspls#42]
If I put url = "https://www.stephenspencerdavis.com/recent-work/" into feeds.toml, then it gives:

```
 INFO  rsspls::feed > processing https://www.stephenspencerdavis.com/recent-work/
 ERROR rsspls       > error processing feed for https://www.stephenspencerdavis.com/recent-work/

Caused by:
    failed to fetch https://www.stephenspencerdavis.com/recent-work/: 400 Bad Request
```

I'm just starting to use rsspls. Another test url I put in seems to not encounter this problem. But the url opens fine in a browser, and the documentation includes another example of a url with a trailing slash, so I don't see why that would be the issue.

Any help you can give would be appreciated.

This is with the Linux x86_64 binary download v. 0.8.1 running on Ubuntu.

**Comment by wezm** [comment]
It seems that they are doing some sniffing of the `User-Agent` header. If you set `user-agent` in the rsspls config it works. In this case I copied the Firefox user agent string on my system:


```toml
[rsspls]
output = "/tmp"

[[feed]]
title = "Test"

filename = "test.rss"

user_agent = "Mozilla/5.0 (X11; Linux x86_64; rv:125.0) Gecko/20100101 Firefox/125.0"

[feed.config]
url = "https://www.stephenspencerdavis.com/recent-work/"

item = ".main-content-inner-wrapper p"

heading = "a"

link = "a"
```

```
 INFO  rsspls::feed > processing https://www.stephenspencerdavis.com/recent-work/
 INFO  rsspls       > write /tmp/test.rss
```
